<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>ADOFAI.EditorToolkit</AssemblyName>
    <RootNamespace>ADOFAI.EditorToolkit</RootNamespace>
    <Version>0.1.1</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
</Project>
